COLS = {
  "competitions": [
    "competition_id", 
    "season_id", 
    "country_name", 
    "competition_name",
    "competition_gender", 
    "competition_youth",
    "competition_international", 
    "season_name"
  ],
  "managers": [
      "id",
      "name",
      "nickname",
      "dob",
      "country"
  ],
  "teams": [
    "team_id",
    "team_name",
    "team_gender",
    "team_group",
    "country",
    "manager_id"
  ],
  "matches": [
    "match_id",
    "match_date",
    "kick_off",
    "home_score",
    "away_score",
    "match_status",
    "match_week",
    "competition_stage",
    "stadium",
    "referee",
    "home_team_id",
    "away_team_id",
    "competition_id",
    "season_id"
  ],
  "lineups": ["match_id", "team_id", "lineup"],
  "events": [
    "id",
    "index",
    "period",
    "timestamp",
    "minute",
    "second",
    "type_id",
    "possession",
    "play_pattern_id",
    "location_x",
    "location_y",
    "position_id",
    "duration",
    "under_pressure",
    "off_camera",
    "counterpress",
    "out",
    "possession_team_id",
    "team_id",
    "player_id",
    "match_id"
  ],
  "tactics": ["event_id", "formation", "lineup"],
  "types": ["id", "name"],
  "positions": ["id", "name"],
  "play_patterns": ["id", "name"],
  "players": ["id", "name"],
  "outcomes": ["id", "name"],
  "techniques": ["id", "name"],
  "body_parts": ["id", "name"],
  "cards": ["id", "name"],
  "heights": ["id", "name"],
  "passes": [
    "event_id",
    "recipient_id",
    "length",
    "angle",
    "height_id",
    "end_location_x",
    "end_location_y",
    "type_id",
    "body_part_id",
    "outcome_id",
    "aerial_won",
    "switch",
    "technique_id",
    "through_ball",
    "deflected",
    "pass_cross",
    "outswinging",
    "assisted_shot_id",
    "shot_assist",
    "no_touch",
    "cut_back",
    "inswinging",
    "straight",
    "goal_assist",
    "miscommunication"
  ],
  "shots": [
    "event_id",
    "xg",
    "end_location_x",
    "end_location_y",
    "end_location_z",
    "key_pass_id",
    "technique_id",
    "body_part_id",
    "type_id",
    "outcome_id",
    "freeze_frame",
    "first_time",
    "open_goal",
    "aerial_won",
    "deflected",
    "saved_off_target",
    "saved_to_post",
    "redirect",
    "follows_dribble"
  ],
  "interceptions": [
    "event_id",
    "outcome_id",
  ],
  "dribbles": [
    "event_id",
    "outcome_id",
    "overrun",
    "nutmeg",
    "no_touch"
  ],
  "half_starts": ["event_id", "late_video_start"],
  "carries": ["event_id", "end_location"],
  "ball_recoveries": [
    "event_id", 
    "recovery_failure", 
    "offensive"
  ],
  "blocks": [
    "event_id",
    "deflection",
    "save_block",
    "offensive"
  ],
  "miscontrols": ["event_id", "aerial_won"],
  "fouls_committed": [
    "event_id",
    "card_id", 
    "type_id", 
    "penalty",
    "advantage",
    "offensive"
  ],
  "fouls_won": [
    "event_id",
    "penalty",
    "advantage",
    "defensive"
  ],
  "duels": ["event_id", "outcome_id", "type_id"],
  "clearances": [
    "event_id",
    "left_foot",
    "body_part_id",
    "aerial_won",
    "head",
    "right_foot",
    "other"
  ],
  "injury_stoppages": ["event_id", "in_chain"],
  "bad_behaviors": ["event_id", "card_id"],
  "substitutions": ["event_id", "replacement_id", "outcome_id"],
  "ball_receipts": ["event_id", "outcome_id"],
  "fifty_fifties": ["event_id", "outcome_id"],
  "goalkeepers": [
    "event_id",
    "outcome_id",
    "shot_saved_off_target",
    "position_id",
    "body_part_id",
    "shot_saved_to_post",
    "technique_id",
    "lost_out",
    "lost_in_play",
    "success_in_play",
    "type",
    "end_location",
    "punched_out"
  ]
}
